### ISSUE TITLE
sliding spliner not significant any time point

### ISSUE THREAD

**Issue by Ahammu** [RRShieldsCutler/splinectomeR#10]
On doing permuspliner test between  groups, I got a p value of 0.034,

#code
result <- permuspliner(data = data2, xvar = 'Time_point', yvar = 'y', cases = 'Subject_ID', category = 'Residence', groups = c('0','1'))

Groups detected: 0 and 1.

Now testing between variables 0 and 1 for a difference in the response labeled y 

Scalpel please: performing permusplinectomy with 999 permutations...

Area between groups successfully calculated, now spinning up permutations...
...permutations completed...

p-value = 0.033_ 

On doing the slidingspliner, I got the plot showing not significant at any time point.  I was expecting the difference at 4 week, but the pvalue showed no significance. How do I explain that,? 

![image](https://user-images.githubusercontent.com/98012710/166902768-a59dd66b-afed-466d-a99b-6bc1c9b80e53.png)
![e shigela](https://user-images.githubusercontent.com/98012710/166902869-b7a6ff76-f301-4280-81f4-8764b7f0bbfa.png)

#code
slide_result <- sliding_spliner(data = data2,
                                xvar = 'Time_point', yvar = 'y',
                                category = 'Residence', groups =c('0','1'), cases = 'Subject_ID', cut_low = 3,
                                ints = 3)

E1 = sliding_spliner.plot.pvals(data = slide_result, xvar = 'Time_point')+
  scale_x_continuous(breaks = c(0.2,1,1.8), labels = c("1 week", "4 weeks", "24 weeks"))

Looking forward to your guidance

Thanks
Sanuja

**Comment by RRShieldsCutler** [comment]
The idea of the sliding test is to see if there are periods where groups diverge significantly, regardless whether the overall trends are different (from the permuspliner function). Often the case is that there's a period of significance even when the overall trend is not significant. But, totally possible to find the opposite, as you might be seeing here! The sliding scale is essentially performing a non-parametric test at each interval. But it's still limited by the number of cases you have (which seems low given the `cut_low` parameter); if you have small sample sizes, the tests will be underpowered.

Just a couple observations: your x-axis is not to scale; you might try using a scale that reflects the timepoints (e.g. instead of c(0.2, 1, 1.8), why not c(1, 4, 24)?). Second, part of the idea here is to use the spline to fill in patterns between data points. So, in addition to fixing the scale, you might want to allow a larger `ints` value. Worth a try!
