### ISSUE TITLE
Input OTU table is Relative abundance or log transformed?

### ISSUE THREAD

**Issue by Jigyasa3** [RRShieldsCutler/splinectomeR#11]
Hi @RRShieldsCutler,

Thanks for a great package! I am following the tutorial on my 16S data. But I was a bit confused about the structure of the OTU table. Could you please confirm if the input OTU table consists of relative abundance or log-transformed data?

Regards
Jigyasa

**Comment by RRShieldsCutler** [comment]
Hello Jigyasa!

Thanks for checking it out! In the vignette, the table is relative abundance. But, the format (relative abundance, log-transformed, CLR, etc.) should not matter, per se, as far as the splinectomeR functions are concerned. The key thing is keeping in mind what impact the format may have on how you interpret the data/results! Hope this helps.

Robin

**Comment by otaviolovison** [comment]
Hello @RRShieldsCutler!

In this paper (https://www.mdpi.com/2073-4425/15/1/51) the authors said that splinectomeR cannot handle compositional data. I decided to check this here on 'issues' section, and found this one, where you say that the input can be CLR data. I just want to confirm that I can use CLR data, since I use a CODA approach in my analyses and I want to use log-ratios (CLR transformed data) as input. 

Thanks in advance!

**Comment by RRShieldsCutler** [comment]
Hi! Well, they don't explain, but I assume they are referring to comparisons with the actual compositional (e.g. relative abundance) data -- not CLR transformed data. In a vignette I show that relative abundance changes can be misleading with these analyses. It will _run_ on most input types if formatted properly, one just needs to keep in mind using and interpreting and being aware of limitations due to proportional or compositional issues. It does not do any transformations as part of the analysis. I am not familiar with specifics of the coda approach but will have to check it out!
