### ISSUE TITLE
Time-series data doubt in category

### ISSUE THREAD

**Issue by ShriramHPatel** [RRShieldsCutler/splinectomeR#5]
Hi, 
Thank you very much for this wonderful package. I  don't have any specific query related to something not working properly in the package.

But I have a query of a time-series data from subjects followed for 3 months at different time intervals. And as a category we have a positive and negative report for bacterial infection in which the patient can be positive for infection at some time-point while at other negative.

So there is a within category variation in and across patients. I even tried running and as expected ran with error saying ""Please ensure that the cases are uniquely labeled between the two groups"".

I would appreciate if you can provide any suggestion on how can we use this kind of data for analysis in this package.

Thanks
Shriram

**Comment by RRShieldsCutler** [comment]
Hello, and thanks for your interest and kind words! You present an interesting issue, and one that we have not experimented with. In truth, the tests were designed assuming consistent group categorization, as you have discovered. How to approach this will depend on your hypothesis, of course. Is it a relevant comparison to categorize patients into Positive and Negative categories, where _any instance of infection_ = Positive, and _no infections_ = Negative? Or some other type of summary (>1 infections, <1 infections...). Unfortunately, I don't think there's a quick or built-in way to deal with flip-flopping categories during the time course. Because of the highly individualized nature of microbiome composition, using the patients' full time series trends is one of the advantages of these tests. If you have enough data points per patient, you could consider breaking up the time courses, so there isn't switching within a patient (but, remember that you need 3-4 points per 'case' to get a decent trend here). Sorry I don't have a quick fix. Happy to help brainstorm some more, if anything here sounds useful...!

**Comment by ShriramHPatel** [comment]
Hi, 
Thanks for your reply,

We have both continuous measurements of infection (in CFU equivalent from RT-PCR) and its categorical (infection=positive and no infection=negative) converted data.
We have a 13 different time-points and will see if breaking the time-series helps in this case or not.
For now, I am planning to apply mixed effect model to find a trend in the data but I would be happy to consider any other approach you can think of and can be helpful for me an other with such interesting case.

Thanks again,
Shriram

**Comment by RRShieldsCutler** [comment]
Neat! Kind of depends what the RTPCR is telling you (targeted taxa or broad detection), but I wonder if a predictive model approach would be interesting. Perhaps this is what you are considering, but if you break the data into each infection instance and the preceding days of RTPCR data, do CFU equivalents of the last 1, 2, 3 days predict the infection vs random days' RTPCR data? Does it perform for some individuals but not others? Or some infections but not others? Sounds like an interesting set of data - if the previous ideas about breaking up enable this package, that's great. But, otherwise it might be more granular or variable than this is designed for, if I'm understanding it correctly. Good luck!
