### ISSUE TITLE
Error in seq.default(from = x.min, to = x.max, by = ((x.max - x.min)/(ints -  :    'from' must be a finite number

### ISSUE THREAD

**Issue by Ahammu** [RRShieldsCutler/splinectomeR#9]
Trying to do a longitudinal analysis of Shannon diversity over time. But only 3 time points- week 1, week 4, week 24 

slide_result <- sliding_spliner(data = div.df,
                                xvar = 'Time', yvar = 'diversity_shannon',
                                category = 'Residence', groups =c('Farm','Control'), cases = 'Subject_ID')

Error in seq.default(from = x.min, to = x.max, by = ((x.max - x.min)/(ints -  : 
  'from' must be a finite number

**Comment by RRShieldsCutler** [comment]
Hello! Ah yes - the `cut_low` parameter is your culprit here. It removes cases (samples) that fall below a set threshold. Default setting for `cut_low` is 4; therefore, it's removing ALL of your samples! Yikes. Change that as below and should help (of course keep in mind possible limitations of extrapolating from three time points - depends on your data and hypotheses!).

```
slide_result <- sliding_spliner(data = div.df,
xvar = 'Time', yvar = 'diversity_shannon',
category = 'Residence', groups =c('Farm','Control'),
cases = 'Subject_ID', cut_low = 3)
```

Cheers!

**Comment by Ahammu** [comment]
Thank you very much!!! 👍   :)  it worked... I had been breaking my head on this since I am new to R.

Thanks again 😊😊

Regards
Sanuja
